### ISSUE TITLE
Missing dev/test data of an-en

### ISSUE THREAD

**Issue by funtion** [EdinburghNLP/opus-100-corpus#1]
Hi,

I noticed that for language pair `an-en`, only the training data is available in the folder https://data.statmt.org/opus-100-corpus/v1.0/supervised/an-en/, but not the validation and test. Can you help have a look?

Thanks

**Comment by funtion** [comment]
Same issue for `dz`: https://data.statmt.org/opus-100-corpus/v1.0/supervised/dz-en/, `hy`: https://data.statmt.org/opus-100-corpus/v1.0/supervised/dz-en/, `mn`: https://data.statmt.org/opus-100-corpus/v1.0/supervised/en-mn/, and `yo`: https://data.statmt.org/opus-100-corpus/v1.0/supervised/en-yo/

**Comment by bzhangGo** [comment]
Hi @funtion, there are five languages in OPUS-100 having no dev/test data. For supervised translation evaluation, we mainly report results for the other 94 language pairs.

**Comment by funtion** [comment]
@bzhangGo Thank you for the clarification!
